name: robfutrell
favicon: null
layout_spectrum: 0.47355864895507693
typography_spectrum: 0.8191551098134369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.20410828106105328
  lightness: 0.288333733798936
  saturation: 0.9047922759782523
  rhythmicContrast: 0.1907740095630288
purpose: []
